### PR TITLE
Added some fixes

### PR DESCRIPTION
**Pull request by SiverDX**
* Single entry point for setBlock (to make it easier if a block should be set)
* Features should now check if they can be placed chunk-wise (this should have fixed the Charred Bones error but it did not)
(I now understand that not all features use the custom placer and some use default Minecraft which does not have this check)
* GroundCoverBlocks now support loot tables if present (mentioned in Curse comment)
* Defaulted loot tables for `twigs` / `pinecones` / `bones`
* GroundCoverBlocks can now only be right-clicked if the hand is empty (allows interaction with water bucket for example, to place or remove water) (Holding certain things like Tools / Weapons seems to count as EMPTY)
(Could maybe change to allow picking up if the item in hand is the same as the block)
* Disabled Charred Bones by default due to their problems
* Fixed duplicate entries for the Item tag of Logs (#189 / #195)
* Rocks now use the intended configuration, meaning no more placement in lava etc.
* Ice Chunks can now spawn on ice
* Snow (layers) should no longer be replaced by features
* Tall Grass and Large Fern should not get cut off anymore
* Rocks now actually spawn in their variants
* Fallen Trees now have the (optional) tags for the already defined modded biomes
* Added Terralith biomes for Fallen Trees

I added a comment in #196 regarding Charred Bones - they seem a bit weird, not sure what's happening there
The solution seems to have fixed it for other mods, e. g.:
https://github.com/Glitchfiend/BiomesOPlenty/blob/cc6c984eeb093cb5749a441e021b3874ca0b6c68/src/main/java/biomesoplenty/common/worldgen/feature/misc/FleshTendonFeature.java#L198

Probably still better to have it I guess?

Thre is a recipe overlap btw that should probably be looked at:
image

The 4x uses the tag `minecraft:spruce_logs` - this is true for all Hollow Logs, maybe they need their own tag or sth.

### CODE REVIEW

**Comment by SiverDX** [comment]
Should probably also add `Blocks.BLUE_ICE` to the check for ice

**Comment by SiverDX** [comment]
Fallen Trees in custom biome and different Rock types spawning:
https://imgur.com/a/WoSC5JM

**Comment by OrderedChaos-Dev** [comment]
Hey thanks for taking the initiative to make these changes. There is a lot in here so I need some time for code review

**Comment by SiverDX** [comment]
yeah this got a bit out of hand
did not really expect any activity at this point

**Comment by Silvertide7** [comment]
I noticed you're trying to merge into the 1.19 branch, but it seems like your repo was forked off of the 1.18 branch?

**Comment by SiverDX** [comment]
> I noticed you're trying to merge into the 1.19 branch, but it seems like your repo was forked off of the 1.18 branch?

where are you seeing that?
grafik

**Comment by Silvertide7** [comment]
Ah, I was looking in the wrong place, my bad!

**Comment by Silvertide7** [comment]
I cloned this and built the jar for my modpack. It fixed everything I was having issues with. Thank you!!

**Comment by OrderedChaos-Dev** [comment]
Hey sorry I haven't been communicating very well. Just merged this and will be going to release the changes once I fix my local dev setup

**Pull request merged**
